-- This file is auto-generated by the migration script
-- for reference purposes only. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS "site" (
	"name"	TEXT,
	"display_name"	TEXT,
	PRIMARY KEY("name")
);
CREATE TABLE IF NOT EXISTS "streamer_sites" (
	"streamer_id"	INTEGER,
	"name"	TEXT,
	"site_id"	TEXT,
	"is_primary"	INTEGER DEFAULT 1,
	"site_name"	TEXT,
	FOREIGN KEY("streamer_id") REFERENCES "streamer"("id"),
	FOREIGN KEY("site_name") REFERENCES "site"("name"),
	UNIQUE("streamer_id","site_name")
);
CREATE TABLE streamer (
    id           INTEGER,
    first_online TIMESTAMP DEFAULT (datetime('now') ),
    last_online  TIMESTAMP DEFAULT (datetime('now') ),
    PRIMARY KEY (
        id
    )
);
