-- This file is auto-generated by the migration script
-- for reference purposes only. DO NOT EDIT.

CREATE TABLE site (
    name TEXT PRIMARY KEY,
    display_name TEXT
);
CREATE TABLE streamer (
    id INTEGER PRIMARY KEY,
    first_online TEXT DEFAULT (datetime('now')),
    last_online TEXT DEFAULT (datetime('now'))
);
CREATE TABLE streamer_sites (
    streamer_id INTEGER,
    name TEXT,
    site_id TEXT,
    is_primary INTEGER DEFAULT 1,
    site_name TEXT,

    FOREIGN KEY (streamer_id) REFERENCES streamer (id),
    FOREIGN KEY (site_name) REFERENCES site (name),
    UNIQUE(streamer_id, site_name)
);
