log_level: INFO
streamlink_cmd: streamlink
streamlink_plugin_path: "/app/plugins"
streamlink_default_stream: best
# Thumbnail generation options. This still fails a decent amount of time.
vcsi_options: "--show-timestamp --width 1920 --grid 8x0 --start-delay-percent 0 --end-delay-percent 0 --interval 10s"
# Download streamer thumbnail when first seen online
download_streamer_thumb: True
# Download streamer thumbnail when marked as new
download_new_streamer_thumb: True
# How often to get new streamer thumbnails
new_streamer_thumb_min: 60
# Ignore streamers with gender male
ignore_male_streamers: True

# Check for streamers online in the last week every minute,
# online in the last month every 5 min, over a month 10 min
online_check_sec:
    in_last_week: 5
    in_last_month: 300
    over_month: 600
# How often to query the APIs for streamers online
api_rate_limit_time_sec: 30
# Once this has been reached, start recording to a new file and process the old one. This does
# appear to be pretty seamless. Depending on how the streamer is managing their stream, sometimes
# this can continue recording when they've kicked people out from the website.
max_recording_min: 59
# The processing seems to mostly be disk access and cpu bound, so this can help the system work
# normally if there are a bunch of files in the to_process folder, or if starting back up after
# an unexpected shutdown.
process_files_at_once: 2
# How many face detection processes to run at once.
detect_faces_at_once: 6
# vcsi seems to have a bug where it doesn't always clean up temp files and can slowly fill up the
# docker container. This should be high enough so it doesn't try and delete any temp files that
# are currently in use.
thumbnail_cleanup_min: 59
#No trailing slash
sites:
    # Remove the api_url field to make the site fall back to checking each
    # individual performer's online status.
    bongacams:
        url: "https://bongacams.com/{username}"
        check_rate_limit_sec: 4
        api_key: "xxxxxx"
        api_url: "https://bcprm.com/promo.php?c={API_KEY}&type=api&api_v=1&api_type=json"
    # This one doesn't seem to be working
    cam4:
        url: "https://www.cam4.com/{username}"
        check_rate_limit_sec: 4
    chaturbate: 
        url: "https://chaturbate.com/{username}"
        check_rate_limit_sec: 6
        api_key: "xxxxxx"
        api_url: "https://chaturbate.com/affiliates/api/onlinerooms/?format=json&wm={API_KEY}"
    stripchat: 
        url: "https://stripchat.com/{username}"
        check_rate_limit_sec: 4
        api_url: "https://go.xlirdr.com/api/models?status=public&limit=0"

streamers:
    # Files are named with this
    MyStreamerName:
        # It will attempt to record at sites based on their order here
        stripchat: MyStreamerName
        bongacams: TheSameStreamerOnBonga
